# Generated by Django 3.0.3 on 2020-02-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=10000)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
